name: Production Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies and tools
        run: npm install -g conventional-changelog-cli

      - name: Generate Production Changelog
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for production release"
          git push origin main

